# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [1]:
import numpy as np
a=np.random.randint(1,21,(5,6))
print(a)
a[:,2]=1
print('\nElements in the third column with 1')
print(a)

b=np.arange(1,17).reshape(4,4)
print("\nOriginal array:")
print(b)
np.fill_diagonal(b, 0)
print("Modified array:")
print(b)

[[ 5  6  5  2 15  7]
 [19  5  5 16  7 15]
 [ 3 17 11 10 20  7]
 [ 2 20 20 15 16 19]
 [ 2  2  3  7  9 17]]

Elements in the third column with 1
[[ 5  6  1  2 15  7]
 [19  5  1 16  7 15]
 [ 3 17  1 10 20  7]
 [ 2 20  1 15 16 19]
 [ 2  2  1  7  9 17]]

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [2]:
c=np.arange(1,37).reshape(6,6)
print(c)
print(c[2:5,1:4])

d=np.random.randint(1,21,(5,5))
print(d)
print(np.concatenate((d[0,:],d[1:-1,-1],d[-1,::-1],d[-2:0:-1,0])))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[17 12 13  9 16]
 [ 8  2 17  8  7]
 [ 1 14  7  1  8]
 [14 20 12 16  3]
 [16  2  8  1 12]]
[17 12 13  9 16  7  8  3 12  1  8  2 16 14  1  8]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [3]:
e=np.random.randint(1,21,(3,4))
f=np.random.randint(1,21,(3,4))
print("e:",e)
print("f:",f)

addition=e+f
subtraction=e-f
multiplication=e*f
division=e/f

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


g=np.random.randint(1,17,(4,4))
print("g:",g)
row_sum=np.sum(g, axis=1)
column_sum=np.sum(g, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

e: [[ 8 12 17  9]
 [12  3 16 12]
 [15  4  4 10]]
f: [[ 7 14  5  6]
 [ 6  4  1 18]
 [15 10  6  4]]
Element-wise addition:
[[15 26 22 15]
 [18  7 17 30]
 [30 14 10 14]]
Element-wise subtraction:
[[ 1 -2 12  3]
 [ 6 -1 15 -6]
 [ 0 -6 -2  6]]
Element-wise multiplication:
[[ 56 168  85  54]
 [ 72  12  16 216]
 [225  40  24  40]]
Element-wise division:
[[ 1.14285714  0.85714286  3.4         1.5       ]
 [ 2.          0.75       16.          0.66666667]
 [ 1.          0.4         0.66666667  2.5       ]]
g: [[16 16  3 10]
 [13  6  1 10]
 [12 16  3  4]
 [ 8 13  2  7]]
Row-wise sum:
[45 30 35 30]
Column-wise sum:
[49 51  9 31]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [4]:
h=np.random.randint(1,21,(5,5))
print("h:",h)
mean=np.mean(h)
median=np.median(h)
std_dev=np.std(h)
variance=np.var(h)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

h: [[ 8  3  3  7 10]
 [ 5 10 20  7 16]
 [13 11 13  2 19]
 [17 17 16 12 20]
 [ 3 13 10  6 19]]
Mean: 11.2
Median: 11.0
Standard Deviation: 5.663920903402519
Variance: 32.080000000000005


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [5]:
i=np.random.randint(1,10,(3,3))
print("i:",i)
n_mean=np.mean(i)
n_std_dev=np.std(i)
normalized_data=(i-n_mean)/n_std_dev
print("Normalized array:",normalized_data)

i: [[5 5 6]
 [3 8 3]
 [8 9 6]]
Normalized array: [[-0.43905704 -0.43905704  0.05488213]
 [-1.42693538  1.04276047 -1.42693538]
 [ 1.04276047  1.53669964  0.05488213]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [6]:
j=np.random.randint(1,11,(3,3))
print("j:",j)
arr=np.array([10,20,30])
print(j+arr)

j: [[ 3 10  4]
 [ 1  8  8]
 [ 4  2  9]]
[[13 30 34]
 [11 28 38]
 [14 22 39]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [7]:
k=np.random.randint(1,11,(4,4))
print("k:",k)
arr=np.array([10,20,30,40])
print(k-arr)

k: [[ 6  1  4  9]
 [ 3  1 10  9]
 [ 2  4  6  9]
 [ 4  1  5  9]]
[[ -4 -19 -26 -31]
 [ -7 -19 -20 -31]
 [ -8 -16 -24 -31]
 [ -6 -19 -25 -31]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [8]:
l=np.random.randint(1,11,(3,3))
print("l:",l)
determinant=np.linalg.det(l)
print("Determinant:", determinant)

inverse=np.linalg.inv(l)
print("Inverse:",inverse)

eigenvalues=np.linalg.eigvals(l)
print("Eigenvalues:", eigenvalues)


l: [[10  5  6]
 [ 6  4  2]
 [ 5  1  2]]
Determinant: -34.00000000000002
Inverse: [[-0.17647059  0.11764706  0.41176471]
 [ 0.05882353  0.29411765 -0.47058824]
 [ 0.41176471 -0.44117647 -0.29411765]]
Eigenvalues: [15.4700877  -1.24102908  1.77094137]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [9]:
m=np.random.randint(1,11,(2,3))
print("m:",m)
n=np.random.randint(1,11,(3,2))
print("n:",n)

matrix_mul=np.dot(m,n)
print("matrix_multiplication:",matrix_mul)

m: [[10 10  8]
 [ 2  5 10]]
n: [[8 5]
 [4 7]
 [8 4]]
matrix_multiplication: [[184 152]
 [116  85]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [10]:
o=np.random.randint(1,10,(3,3))
print("o:",o)

reshaped_array_1=o.reshape(1,9)
print("Reshaped array (1, 9):",reshaped_array_1)

reshaped_array_2=o.reshape(9,1)
print("Reshaped array (9,1):",reshaped_array_2)

o: [[5 9 9]
 [3 1 9]
 [2 7 5]]
Reshaped array (1, 9): [[5 9 9 3 1 9 2 7 5]]
Reshaped array (9,1): [[5]
 [9]
 [9]
 [3]
 [1]
 [9]
 [2]
 [7]
 [5]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [11]:
p=np.random.randint(1,11,(5,5))
print("p:",p)

flat=p.flatten()
print("Flatten",flat)

reshaped_flatten=p.reshape(5,5)
print("Reshaped flatten: ",reshaped_flatten)

p: [[ 2  1  6  5  4]
 [ 1  7  9  4  7]
 [ 8 10  3  2  7]
 [ 7  4  3  9  8]
 [ 4  6  4  7  5]]
Flatten [ 2  1  6  5  4  1  7  9  4  7  8 10  3  2  7  7  4  3  9  8  4  6  4  7
  5]
Reshaped flatten:  [[ 2  1  6  5  4]
 [ 1  7  9  4  7]
 [ 8 10  3  2  7]
 [ 7  4  3  9  8]
 [ 4  6  4  7  5]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [12]:
q=np.random.randint(1,11,(5,5))
print("q:",q)

corners=q[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:",corners)

q: [[ 9 10  6  6  2]
 [ 9  2  3  4  8]
 [ 7  6  1  2 10]
 [ 2  9  9  9  7]
 [ 1  3  7  8  2]]
Corner elements: [9 2 1 2]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [13]:
r=np.random.randint(1,21,(4,4))
print("r:",r)

r[r>10]=10
print("Modified array:",r)


r: [[15 12  5  1]
 [ 7 15 20  5]
 [16 11  3  7]
 [16  3 12 14]]
Modified array: [[10 10  5  1]
 [ 7 10 10  5]
 [10 10  3  7]
 [10  3 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [14]:
data_type=[('name','U10'), ('age','i4'), ('weight','f4')]
s=np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(s)

sorted_data=np.sort(s, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [15]:
data_type=[('x', 'i4'), ('y', 'i4')]
t=np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(t)

distances=np.sqrt((t['x'][:, np.newaxis]-t['x'])**2 + (t['y'][:, np.newaxis] - t['y'])**2)
print("Euclidean distances:")
print(distances)    

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [16]:
import numpy.ma as ma

array=np.random.randint(1, 21,(4, 4))
masked_array=ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

sum_unmasked=masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 8 17  6 15]
 [11 17 17 18]
 [13 15 17 19]
 [11 18 18 10]]
Masked array:
[[8 -- 6 --]
 [-- -- -- --]
 [-- -- -- --]
 [-- -- -- 10]]
Sum of unmasked elements: 24


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [17]:
array=np.random.randint(1, 21, size=(3, 3))
masked_array=ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

mean_unmasked=masked_array.mean()
masked_array=masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[19  4 13]
 [ 7  7  8]
 [ 3 19  7]]
Masked array:
[[-- 4 13]
 [7 -- 8]
 [3 19 --]]
Modified masked array:
[[ 9  4 13]
 [ 7  9  8]
 [ 3 19  9]]
